version: '2'
services: 
    web: 
        build: ./
        privileged: true
        ports: 
            - "5000:5000"
        environment:
            MONGO_PORT : 27017
            MONGO_HOST : mongo
            MONGO_DB : joinble
            MONGO_URI : mongodb://mongo:27017/joinble
            PORT : 5000
        restart: always
        volumes: 
            - ".:/home/web"
        depends_on:
            - mongo
    mongo:
        image: mongo
